[package]
name = "printable"
version = "0.1.0"
edition = "2021"
git = "https://github.com/emm312/printable"
license = "MIT"
description = "A crate to add member functions for printing"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
